import keyMirror from 'key-mirror'

export default keyMirror({
    ALERT_SUCCESS: null,
    ALERT_ERROR: null,
    ALERT_CLEAR: null,

    USERS_REGISTER_REQUEST: null,
    USERS_REGISTER_SUCCESS: null,
    USERS_REGISTER_FAILURE: null,

    USERS_LOGIN_REQUEST: null,
    USERS_LOGIN_SUCCESS: null,
    USERS_LOGIN_FAILURE: null,

    USERS_LOGOUT: null,

    USERS_GETALL_REQUEST: null,
    USERS_GETALL_SUCCESS: null,
    USERS_GETALL_FAILURE: null,

    USERS_DELETE_REQUEST: null,
    USERS_DELETE_SUCCESS: null,
    USERS_DELETE_FAILURE: null,

    START_LOADING_ACIDENTS: null,
    END_LOADING_ACIDENTS: null,
    FETCH_ACIDENTS_LIST_BY_BATCH: null,
    FETCH_ACIDENTS_LIST_FIRST_LOAD: null,
    FETCH_ACIDENTS_LIST: null,
    SELECT_ACIDENT: null
})